import type { Metadata } from "next";
import "../styles/globals.css";
import "antd/dist/reset.css";
import "@ant-design/v5-patch-for-react-19";
import { ConfigProvider } from "antd";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider
          theme={{
            token: { colorPrimary: "#F54927" },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
