import type { Metadata } from "next";
import "../styles/globals.css";
import "antd/dist/reset.css";
import "@ant-design/v5-patch-for-react-19";
import { ConfigProvider } from "antd";
import QueryProvider from "@/store/query-provider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster position="top-center" />
        <ConfigProvider
          theme={{
            components: {
              Button: {
                // defaultBg: "#13C110",
                // defaultActiveBg: "#13C110",
              },
            },
          }}
        >
          <QueryProvider>{children}</QueryProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
